### ISSUE TITLE
Publish as NPM package

### ISSUE THREAD

**Issue by mourner** [padolsey/findAndReplaceDOMText#28]
NPM is becoming the de-facto standard repository of JS modules, both browser and server. So it would be nice to have this published there.

**Comment by krawaller** [comment]
+1

**Comment by badsyntax** [comment]
+1, would be useful, needs some UMD love.

**Comment by padolsey** [comment]
Agreed, just made 0.4.3 available on npm: https://www.npmjs.com/package/findandreplacedomtext

**Comment by mourner** [comment]
Awesome, thanks!

**Comment by badsyntax** [comment]
Can I suggest something along the lines of... 

```js
(function (root, factory) {
	if (typeof module === 'object' && module.exports) {
		// Node/CommonJS
		module.exports = factory();
	} else if (typeof define === 'function' && define.amd) {
		// AMD. Register as an anonymous module.
		define(factory);
	} else {
		// Browser globals
		root.findAndReplaceDOMText = factory();
	}
}(this, function factory() {

	function exposed() {
	}

	return exposed;
}));
```
.. along with a change to `package.json` to specify main entrypoint.

**Comment by mourner** [comment]
@padolsey yeah, one grip remaining — it's only exported as a browser global, which makes it impossible to use with build systems like Browserify and Webpack.
