### ISSUE TITLE
Appending text at the end of matched element?

### ISSUE THREAD

**Issue by Schezuk** [padolsey/findAndReplaceDOMText#34]
I have a dictionary function dict() which append result after input string
```
function dict (match){return match +dictionary[match] }
```

I want to edit text of elements like 
```
document.body.innerHTML = document.body.innerHTML.replace(/something/g, dict());
```
does, but without messing up tags' name and properties like 'src'.

I am confused with 'portion' and 'match' in your method 'replace'. 
Could you give me a simple demo? Thank you.

**Comment by padolsey** [comment]
You'd probably want to append your dictionary item to the very last portion. A portion is a part of a match -- if a match is non-contiguous (goes through element borders) then it'll have multiple portions.

See http://jsfiddle.net/hmfp1eqn/ (notice how the appended `(something)` is within the last portion)

Hope that helps.

**Comment by Schezuk** [comment]
Many Thanks!
