### ISSUE TITLE
"Everything to the left of the match" not working as expected

### ISSUE THREAD

**Issue by rileyjshaw** [padolsey/findAndReplaceDOMText#35]
Thanks for the awesome library! :)

From the docs, `` $` `` should represent everything to the left of the match. I was hoping that meant _"to the left of the 1st captured group"_, but it seems that I misunderstood. Running this:

```
findAndReplaceDOMText(document.body, {
    preset: 'prose',
    find: /Specific Words \((\d+)/g,
    replace: '$`0',
});
```

On a document containing:

```
Specific Words (123)
```

Winds up as:

```
Specific Words (123)0
```

When I would expect:

```
Specific Words (0)
```

Any advice?

**Comment by padolsey** [comment]
I've tried to emulate the <code>[String#replace](http://www.ecma-international.org/ecma-262/5.1/#sec-15.5.4.11)</code> method in this lib, so <code>$`</code> will replace "the portion of string that precedes the matched substring", as in everything that precedes the entire match of the regex, regardless of captures.

Traditionally you might use a positive-lookbehind but these aren't supported in JS' RegExp implementation. So, I think the best way to do what you want is to capture the "Specific words" portion, and specifically replace it with itself, so something like:

```js
findAndReplaceDOMText(document.body, {
    preset: 'prose',
    find: /(Specific Words )\(\d+/g,
    replace: '$1(0'
});
```

**Comment by rileyjshaw** [comment]
Oh! That makes sense, I had no idea that these replacement symbols were part of the actual spec. Thanks (as always) for the thorough response, it's much clearer now.

Closing, as there's not actually an issue here :)
