### ISSUE TITLE
Search/replace also replaces within comments

### ISSUE THREAD

**Issue by J7mbo** [padolsey/findAndReplaceDOMText#42]
I require the ability to find/replace throughout the _whole_ document.

```
findAndReplaceDOMText(document, {find: text, wrap: wrapElem});
```

Funnily enough, if text is equal to `Hello World` and I have a comment in my Javascript like `/** Contains "Hello World" **/`, this is also matched and replaced, causing issues when getting a list of all the newly wrapped elements.

I don't know the best way to fix this as there are different (all legitimate) ways of commenting in Javascript from `/* */` to `//`. I'm not sure if there are any more. Given a list of comment types (which could easily be modified in the future), perhaps we could ignore any where they exist around the match?

**Comment by padolsey** [comment]
You'll want to instruct `findAndReplaceDOMText` to avoid `SCRIPT` elements. But you'll also want to avoid a bunch of other non-prose-containing elements like `STYLE` and `VIDEO`, etc.

Fortunately there's a "prose" preset which does this all for you :)

```js
findAndReplaceDOMText(document.body, {
  preset: 'prose',
  find: 'foo',
  replace: 'bar'
});
```

Or you could manually avoid `SCRIPT` elements like so:

```js
findAndReplaceDOMText(document.body, {
  filterElements: function(el) {
    return el.nodeName.toLowerCase() !== 'script';
  },
  find: 'foo',
  replace: 'bar'
});
```

Hope that helps!
