### ISSUE TITLE
Matching across newlines?

### ISSUE THREAD

**Issue by giorgio79** [padolsey/findAndReplaceDOMText#47]
Noticed the function is not matching over newlines. Here is the fiddle
http://jsfiddle.net/nk34mbs3/3/

**Comment by jdreesen** [comment]
Well, your regex doesn't allow any newlines or multiple spaces (the text is indented after the linebreak).

Try something like this `find: new RegExp('Use this stuff with Google Chrome for best results!'.split(' ').join('[\\s\\S]+'))`
