### ISSUE TITLE
findAndReplaceDOMText creating multiple spans during replace, if another html element is in between

### ISSUE THREAD

**Issue by giorgio79** [padolsey/findAndReplaceDOMText#48]
Demo 
http://jsfiddle.net/nk34mbs3/4/

![image](https://cloud.githubusercontent.com/assets/283347/18610593/b0985036-7d20-11e6-812e-1fb7185f47c4.png)

**Comment by giorgio79** [comment]
Looks like as of HTML5 such overlapping html tags are OK
http://stackoverflow.com/questions/28840281/are-overlapping-html-formatting-tags-always-a-bad-practice

Could we have an option, so that overlapping tags are ok, and only a single html element is added by FindandreplaceDOMText?

**Comment by jdreesen** [comment]
There are no overlapping tags, just nested spans. And nesting inline elements is (and, I think, always was) perfectly valid.

Inserting only a single tag around the whole match instead may result in invalid nesting because there may be a block element (like a div) in the match and it's not allowed to nest block elements inside inline elements.

**Comment by giorgio79** [comment]
Ok, but if there are only inline elements, it would be great to allow such overlapping nesting. Perhaps as an option in FindandReplaceDOMTEXT.
So, I would like to be able to do a find and replace, so the resulting html will look like this
before

<div> Hell <span>o</span></div>

<div> H<span id="findandreplacedom"> ell <span>o</span></span></div>

So, I want to avoid extra spans or elements at node boundaries as is the default currently.

**Comment by cloudtracer** [comment]
I've come across use cases where I needed to manage weirdly used tags that chop up text of interest before and this is how I dealt with them.  You may need to modify the matches if for different scenarios but you get the idea.

http://jsfiddle.net/nk34mbs3/5/
