### ISSUE TITLE
Regex Behaviour Clarification

### ISSUE THREAD

**Issue by jonaslund** [padolsey/findAndReplaceDOMText#49]
Great script!! 

Question, when matching regex's, each of the matches gets called multiple times?

```js
findAndReplaceDOMText($("body")[0], {
  preset: 'prose',
  find: /(bananas are cool)|(i prefer oranges)|(super foo bar)/gi,
  replace: function(portion, match) {

    //called on every match if it doesn't match?    
    return match + " i totally agree";
   
  }      
});
```

**Comment by padolsey** [comment]
The `replace` function will get called on *every* portion of *every* match. [More info here](https://github.com/padolsey/findAndReplaceDOMText#the-replace-function).

**Comment by jonaslund** [comment]
Thx
