### ISSUE TITLE
wrap with tag attributes

### ISSUE THREAD

**Issue by drshrey** [padolsey/findAndReplaceDOMText#51]
Hey James, this is an awesome library. However, I want to be able to add attributes like `title` to my `span` tags I wrap with. Is that already possible?

**Comment by padolsey** [comment]
Yep, the `replace` option can be a function (returning a DOM node), e.g.

```js
findAndReplaceDOMText(document.body, {
  find: 'something',
  replace: function(portion) {
  	var span = document.createElement('span');
    span.title = portion.text;
    span.textContent = portion.text;
    return span;
  }
})
```

Note that your `replace` function might be called more than once on a single match, e.g. if the match is split across multiple nodes resulting in multiple matched "portions". See [this for more info on portions](https://github.com/padolsey/findAndReplaceDOMText#what-is-a-portion).

**Comment by drshrey** [comment]
That's perfect (and I just noticed it in the docs too 😅 ). Thanks!
