### ISSUE TITLE
replacing a word doesn't work in certain conditions

### ISSUE THREAD

**Issue by arjhun** [padolsey/findAndReplaceDOMText#52]
Hi James, 

when i use a regex of /**\btrump\b**/gi in my chrome extension that looks for the exact word in a document body it works on most sites. But sometimes like on a google search result page it doesn't work on the result titles. This happens when the word i'm looking for is the first or last word in a sentence?! So I changed the regex to /**(trump|donald)**/gi instead of /**\b(trump|donald)\b**/gi. But now, off course, also trumpet and mcDonald will be matched. I hope you can help me out!

**Comment by padolsey** [comment]
Your regex is fine -- but I do recommend using the `preset:'prose'` option which ensures that non-inline elements (e.g. DIV) are not matched across. Without this option (and by default), the matcher will consider things like `<div>omg</div>trump` to not match `/\btrump\b/` as all it sees is `omgtrump` as a single string of characters.

Specifying `preset:'prose'` will force all non-inline elements to have their own matching contexts, and to ignore all non-prose elements like STYLE and SCRIPT. See https://github.com/padolsey/findAndReplaceDOMText#contexts for more info.

**Comment by arjhun** [comment]
thanks so much! This fixes that issue... I guess it's almost impossible to create a catch all solution for every site on the web, because other problems now occur. For instance:

`/donald trump|\b(trump|donald)\b/gi` on  `Donald <em>Trump</em>`
replace with apple
- without `preset 'prose'`:
 - result: apple (desired result)
- with `preset 'prose'`:
 - result: apple apple
 
(I read your blog, i'm starting to understand why finding and replacing within the DOM is so tricky!)

Thanks!

**Comment by padolsey** [comment]
Could you put up a JSFiddle with the error cases you're seeing? I just tried it and it seems to work fine.

**Comment by arjhun** [comment]
I think I identified the problem wrongly... sorry for that. This jsfiddle shows what happens: https://jsfiddle.net/arjhun/fwzyxkkt/

**Comment by padolsey** [comment]
Ah, I see..

If you use a function as the `replace` option then it'll get called on every portion of every match, not just on every match (there may be several portions to a single match). So, e.g., in your JSFiddle there are actually 2 portions to your match:

```html
donaldj<b>trump</b>
^^^^^^^   ^^^^^
```

Does that make sense? Depending on what you want to achieve, you could define the `replace` option as a string, and then you'd get the desired result:

```js
findAndReplaceDOMText(document.getElementById("test"), {
    find: trumpRegex,
    replace: 'apple',
    preset:'prose'
});
```

**Comment by arjhun** [comment]
Thank you so much for your help and great script! It's a bit brute force hack n slash but working ok... https://github.com/arjhun/agent-orange closing!
