### ISSUE TITLE
Replace text within element's 'title' attribute

### ISSUE THREAD

**Issue by jalbao** [padolsey/findAndReplaceDOMText#53]
It appears as though fARDT will only replace text that exists within the contents of an element as opposed to any/all text that exists within the entire document. 

Is there an option that will replace text that exists within the attributes of an element?

Example: 
How to replace the text within the 'title' attribute of all 'img' tags. So <img title="foo" /> can be changed to <img title="bar" />.

**Comment by padolsey** [comment]
To be honest that is a much more self-contained problem that can be handled without findAndReplaceDOMText, e.g.

```js
[].slice.call(document.querySelectorAll('img')).forEach(function(img) {
	if (img.title) {
		img.title = img.title.replace(/foo/gi, 'bar');
	}
});
```

**Comment by jalbao** [comment]
Sorry, I wasn't clear in my previous comment...

The HTML document that I am working with contains strings that can exist anywhere within the entire documents.

Example:
```
<!DOCTYPE html>
<html>
<head>
    <title>#REPLACEME.FOO#</title>
    <link rel="stylesheet" href="#REPLACEME.BAR#" />
</head>
<body>
<div>Hello, #REPLACEME.FOOBAZ#</div>

<a href="somepage.html" download="#REPLACEME.FOOBAZ#">
  <img src="pic.jpg" title="#REPLACEME.BARBAZ# /> Save
</a>

<span>findAndReplaceDOMText is awesome and #REPLACEME.BAZ#</span>
</body>
</html>
```

All of the strings in the format "#REPLACEME...#" are the strings that I need to replace with something else. Notice how the strings can be placed anywhere within the document.

findAndReplaceDOMText works great (especially since it doesn't affect event listeners!), but I have noticed that it does not replace text that exists within an HTML tag.

**Comment by padolsey** [comment]
This seems like a tricky thing to do non-destructively, as you'd have to essentially have to loop through all the document's elements and then proceed to to a find-and-replace in each attribute. Is there no way you can do this on the server-side?

Either way, replacing attributes is outside the scope of findAndReplaceText unfortunately -- as it only deals with the innerText of elements/text-nodes. Sorry that I can't be any more helpful.
