### ISSUE TITLE
Why is it not finding any matches?

### ISSUE THREAD

**Issue by entheologist** [padolsey/findAndReplaceDOMText#54]
I added it to a chrome extension so I can test it on any page. I used this code to test:
```
var test = findAndReplaceDOMText(document.getElementsByTagName("p"), {
  find: /\w+/g,
  wrap: 'b'
});
console.log(test);
```

but no matter what I try, it returns no matches:
https://i.gyazo.com/f9dfc2024e7edc98bd938409f632a81b.png

What I need to do is select a bunch of tags with JQuery, search for a regular expression and replace them with a pattern. But I can't get it to work at all.

**Comment by padolsey** [comment]
Could you post an example of it not working to [JSFiddle](http://jsfiddle.net) (So I can have a look)?
