### ISSUE TITLE
Can I ignore the beginning of my regex match when wrapping it with an element?

### ISSUE THREAD

**Issue by jkupczak** [padolsey/findAndReplaceDOMText#57]
I'm using `/Subscribe/gi` as my regex. What I'm trying to do is highlight the word "Subscribe" by wrapping it in a `span` element. I was getting matches to "Unsubscribe" though, so I adjusted my regex to include `[^n]`. Now it reads `/[^n]Subscribe/gi`. This solved my problem for a moment. Unfortunately, this now matches "Subscribe" when it's at the beginning of a text node because the previous text node butts up against it. `[^n]` matches whatever that character happens to be at the end of the previous node.

Here's my code:

```
findAndReplaceDOMText(document.getElementsByTagName('body')[0], {
    find: /[^n]Subscribe/gi,
    wrap: 'span',
    wrapClass: "text-error"
  });
```

Here's a working example of what I'm talking about on Codepen: http://codepen.io/jimmykup/pen/ggLdja

You can see that it breaks my table in the left example (compare it to the table on the right). Is there something I could be doing with findAndReplaceDOMText or a way to better structure my RegEx to avoid instances like this? Ideally, if it could just ignore anything that matches [^] when wrapping it with an element that would work, but I don't know if that can be done.

**Comment by jdreesen** [comment]
I think you could enclose it with `\b` ([word boundry](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#special-word-boundary)) like this: `find: /\bSubscribe\b/gi`.

**Comment by jkupczak** [comment]
Fantastic tip. Thank you!
