### ISSUE TITLE
Issue with regular expressions in lists due to getAggregateText

### ISSUE THREAD

**Issue by spxdcz** [padolsey/findAndReplaceDOMText#58]
If I use a regular expression with word boundaries, and attempt to match it over a set of list elements, e.g. `/\bitem\b/` over

```
<ul>
  <li>item</li>
  <li>item</li>
  <li>item</li>
<ul>
```

it won't match the text in the li elements because getAggregateText will concatenate them all together as `itemitemitem`

**Comment by padolsey** [comment]
I suspect your HTML is minified, so the actual DOM is closer to:

```html
<ul><li>item</li><li>item</li><li>item</li><ul>
```

The default functionality of `findAndReplaceDOMText` is to assume all elements are essentially inline (and thus it'll match contiguous text across node boundaries). To avoid this in the case of block-level elements (like `<li>`) you'll probably want to use `preset: 'prose'` in your config ([docs](https://github.com/padolsey/findAndReplaceDOMText#presetprose)) -- this forces all traditionally block-level elements to have their own context.

Or you could explicitly force the context just for `<li>` like so ([demo](https://jsfiddle.net/f9e7jdhy/)):

```js
findAndReplaceDOMText(document.body, {
  find: /\bitem\b/g,
  replace: 'foo',
  forceContext: function(el) {
  	return el.nodeName.toLowerCase() === 'li';
  }
});
```
