### ISSUE TITLE
Exclude certain elements from replace

### ISSUE THREAD

**Issue by csf30816** [padolsey/findAndReplaceDOMText#63]
I use this to replace things, but I would like to know if there was a way to not let it replace things in certain elements, like textarea's etc. Thanks!

**Comment by padolsey** [comment]
Yes, I recommend using `preset:'prose'`. Docs **[here](https://github.com/padolsey/findAndReplaceDOMText#presetprose)**.

**Comment by csf30816** [comment]
Thanks, I will try that. I will tell you if I face any issues, ok?

**Comment by padolsey** [comment]
(Presuming this worked ok? If not, please let me know.)
