### ISSUE TITLE
[question]  add a class to the tag that contains the text

### ISSUE THREAD

**Issue by pouledodue** [padolsey/findAndReplaceDOMText#65]
hi
Is it possible to get [this behavior](https://stackoverflow.com/a/7896669) with findAndReplaceDOMText?

I want to add a class to the tag that contains the text

example:
if I have
```
<body>
<div>
   <p>yoshi</p>
</div>
   <p>
      <li>    
      <p>yoshi</p>
       </li>
    </p>
</body>
```

I need
```
<body>
<div>
   <p CLASS_ADDED>yoshi</p>
</div>
   <p>
      <li>    
      <p CLASS_ADDED>yoshi</p>
       </li>
    </p>
</body>
```

The goal is to hide the nodes that contain variations of `yoshi` text..
So in this particular case, CLASS_ADDED would be `class="hide_me"` 

I've tested but
```
    findAndReplaceDOMText(container, {
        find: = RegExp("yoshi", 'gi'),
        ....??????....
    })
```

**Comment by padolsey** [comment]
Something like this should work:

```js
findAndReplaceDOMText(document.body, {
  find: /yoshi/gi,
  replace: function(portion) {
    portion.node.parentNode.className = 'yoshi';
    return portion.text;
  }
});
```

Demo: https://jsfiddle.net/shte9qpo/

**Comment by pouledodue** [comment]
oh that's really great, thanks a lot
