### ISSUE TITLE
Empty values in optional capture groups are rendered as undefined

### ISSUE THREAD

**Issue by ardcore** [padolsey/findAndReplaceDOMText#70]
When using `replace` with optional capture groups findAndReplaceDOMText seems to replace empty capture group values with `undefined` in HTML (instead of empty string). Example: 

```js
findAndReplaceDOMText(context, {
  find: /(This)(\s+)?(document),
  replace: "$1$2$3",
});
```
ran against `Thisdocument` (in HTML) will result in `Thisundefineddocument`

**Comment by padolsey** [comment]
Hmm, am having a hard time reproducing: https://jsfiddle.net/fdqcsy9p/

Could you post the specific code that breaks if possible? Or create a small failing test case / fiddle?

**Comment by ardcore** [comment]
https://jsfiddle.net/ef5z8j0g/

**Comment by padolsey** [comment]
Should be [fixed](https://github.com/padolsey/findAndReplaceDOMText/commit/59e642cf8d1ce8e1a13dfaecc0a6db16100c6c26#diff-b0c43ad395c8b3aaf979133f5dc20b9bR466) in v0.4.6.

**Comment by padolsey** [comment]
(Thanks for reporting this! And lemme know if you find any other weird bugs.)

**Comment by ardcore** [comment]
Thanks for the quick turnaround!
