### ISSUE TITLE
Match text only if it's not split across DOM nodes

### ISSUE THREAD

**Issue by jkupczak** [padolsey/findAndReplaceDOMText#74]
I know that the `prose` option allows this for block level elements. But as it mentions:

- Note: matches will still be able to cross textual-inline element borders (`<em>`, `<span>`, etc.)

Is there any way to exclude matches that have textual-inline element borders like `<span>`?

**Comment by hftf** [comment]
Are you looking for `forceContext`?

**Comment by jkupczak** [comment]
How did I miss that. Thank you.
