### ISSUE TITLE
Allow passing data to stencil nodes

### ISSUE THREAD

**Issue by josiahcoad** [padolsey/findAndReplaceDOMText#79]
When I pass a simple stencil node to wrap, I want to be able to pass data to the stencil node.

**Comment by padolsey** [comment]
What kind of data do you want to pass? Data from the match itself? Have you tried using a custom `replace` function? (these can return Nodes)

Alternatively, you can hack something together, as long as it provides a outerHTML/nodeType. E.g. if you wanted a prefixed index attached to each match:

```js
var index = 0;

findAndReplaceDOMText(document.querySelector('div'), {
  find: /blah/gi,
  wrap: {
    nodeType: 1,
    outerHTML: {
      toString: function() {
        return '<strong>' + ++index + '...</strong>';
      }
    }
  }
});

```

Demo: https://jsfiddle.net/g9sywub6/1/

If you need actual match data so you can process it somehow then I definitely suggest using the `replace` option.

**Comment by josiahcoad** [comment]
Great! This does it, thanks!
